#!/usr/bin/expect -f

set user_host [lindex $argv 0]
set passwd [lindex $argv 1]
set flag [lindex $argv 2]

spawn ssh $user_host
expect "$user_host's password: "
send "$passwd\r"
sleep .2

send -- "\x1B\[B"
sleep .1
send -- "\x1B\[B"
sleep .1
send -- "\x1B\[B"
sleep .1
send -- "\x1B\[B"
sleep .1
send -- "\x1B\[B"
sleep .1
send -- "\r"
sleep .1
send -- "s\r"
sleep .1
send "$flag"
send "\r"
sleep 1
send "\003"
