#!/usr/bin/expect -f

set user_host [lindex $argv 0]
set passwd [lindex $argv 1]
set admin_passwd [lindex $argv 2]

spawn ssh $user_host
expect "$user_host's password: "
send "$passwd\r"
sleep .2
expect "*"
send -- "\r"
sleep .1
send -- "$admin_passwd"
sleep .1
send "\r"
sleep .5
send -- "\r"
sleep .1
send -- "y"
send -- "\r"
sleep 2
